version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: docker_mysql_flask_app
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
